name: Build bpftrace v0.24.2 static (arm64)

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04-arm

    steps:
      - name: Checkout bpftrace v0.24.2
        uses: actions/checkout@v4
        with:
          repository: bpftrace/bpftrace
          ref: v0.24.2

      - name: Build static build environment
        run: ./.github/include/static-arm64.sh